### ISSUE TITLE
Update Team.md for the summer

### ISSUE THREAD

**Issue by yamgent** [se-edu/se-edu#7]
`Team.md` needs to be updated, for the progress that was made in the summer:

~~* @pyokagan as project mentor.~~
~~* @Zhiyuan-Amos and @limmlingg as committers.~~
~~* Any other updates deemed necessary.~~

Follow the list as per https://github.com/se-edu/se-edu.github.io/issues/7#issuecomment-314306783.

**Comment by Zhiyuan-Amos** [comment]
@yamgent as Team Lead?

**Comment by damithc** [comment]
Update as follows:
Damith: Project Adviser
Paul, Huang Chao: Project Mentor
Wang Leng: Project Lead
Zhi Yuan: Area Lead (Logic)
Miao Ling, Jeremy, Pierce: committers
Others currently listed as core members or committers: past members
